export const booksInfo = {
	gn: { name: 'Gênesis', chapters: 50 },
	ex: { name: 'Êxodo', chapters: 40 },
	lv: { name: 'Levítico', chapters: 27 },
	nm: { name: 'Números', chapters: 36 },
	dt: { name: 'Deuteronômio', chapters: 34 },
	js: { name: 'Josué', chapters: 24 },
	jz: { name: 'Juízes', chapters: 21 },
	rt: { name: 'Rute', chapters: 4 },
	'1sm': { name: '1º Samuel', chapters: 31 },
	'2sm': { name: '2º Samuel', chapters: 24 },
	'1rs': { name: '1º Reis', chapters: 22 },
	'2rs': { name: '2º Reis', chapters: 25 },
	'1cr': { name: '1º Crônicas', chapters: 29 },
	'2cr': { name: '2º Crônicas', chapters: 36 },
	ed: { name: 'Esdras', chapters: 10 },
	ne: { name: 'Neemias', chapters: 13 },
	et: { name: 'Ester', chapters: 10 },
	job: { name: 'Jó', chapters: 42 },
	sl: { name: 'Salmos', chapters: 150 },
	pv: { name: 'Provérbios', chapters: 31 },
	ec: { name: 'Eclesiastes', chapters: 12 },
	ct: { name: 'Cânticos', chapters: 8 },
	is: { name: 'Isaías', chapters: 66 },
	jr: { name: 'Jeremias', chapters: 52 },
	lm: { name: 'Lamentações de Jeremias', chapters: 5 },
	ez: { name: 'Ezequiel', chapters: 48 },
	dn: { name: 'Daniel', chapters: 12 },
	os: { name: 'Oséias', chapters: 14 },
	jl: { name: 'Joel', chapters: 3 },
	am: { name: 'Amós', chapters: 9 },
	ob: { name: 'Obadias', chapters: 1 },
	jn: { name: 'Jonas', chapters: 4 },
	mq: { name: 'Miquéias', chapters: 7 },
	na: { name: 'Naum', chapters: 3 },
	hc: { name: 'Habacuque', chapters: 3 },
	sf: { name: 'Sofonias', chapters: 3 },
	ag: { name: 'Ageu', chapters: 2 },
	zc: { name: 'Zacarias', chapters: 14 },
	ml: { name: 'Malaquias', chapters: 4 },
	mt: { name: 'Mateus', chapters: 28 },
	mc: { name: 'Marcos', chapters: 16 },
	lc: { name: 'Lucas', chapters: 24 },
	jo: { name: 'João', chapters: 21 },
	at: { name: 'Atos', chapters: 28 },
	rm: { name: 'Romanos', chapters: 16 },
	'1co': { name: '1ª Coríntios', chapters: 16 },
	'2co': { name: '2ª Coríntios', chapters: 13 },
	gl: { name: 'Gálatas', chapters: 6 },
	ef: { name: 'Efésios', chapters: 6 },
	fp: { name: 'Filipenses', chapters: 4 },
	cl: { name: 'Colossenses', chapters: 4 },
	'1ts': { name: '1ª Tessalonicenses', chapters: 5 },
	'2ts': { name: '2ª Tessalonicenses', chapters: 3 },
	'1tm': { name: '1ª Timóteo', chapters: 6 },
	'2tm': { name: '2ª Timóteo', chapters: 4 },
	tt: { name: 'Tito', chapters: 3 },
	fm: { name: 'Filemom', chapters: 1 },
	hb: { name: 'Hebreus', chapters: 13 },
	tg: { name: 'Tiago', chapters: 5 },
	'1pe': { name: '1ª Pedro', chapters: 5 },
	'2pe': { name: '2ª Pedro', chapters: 3 },
	'1jo': { name: '1ª João', chapters: 5 },
	'2jo': { name: '2ª João', chapters: 1 },
	'3jo': { name: '3ª João', chapters: 1 },
	jd: { name: 'Judas', chapters: 1 },
	ap: { name: 'Apocalipse', chapters: 22 },
};
