export const color = {
	tomato: '--tomato-9',
	red: '--red-9',
	ruby: '--ruby-9',
	crimson: '--crimson-9',
	pink: '--pink-9',
	plum: '--plum-9',
	purple: '--purple-9',
	violet: '--violet-9',
	iris: '--iris-9',
	indigo: '--indigo-9',
	blue: '--blue-9',
	cyan: '--cyan-9',
	teal: '--teal-9',
	jade: '--jade-9',
	green: '--green-9',
	grass: '--grass-9',
	brown: '--brown-9',
	orange: '--orange-9',
	sky: '--sky-9',
	mint: '--mint-9',
	lime: '--lime-9',
	yellow: '--yellow-9',
	amber: '--amber-9',
	gold: '--gold-9',
	bronze: '--bronze-9',
	gray: '--gray-9',
};
